Write to output when no casm_output_path provided
software-mansion/universal-sierra-compiler pull request #4
Opened 2023-12-20 18:02 UTC by war-in

2023-12-20 19:13 UTC, piotmag769 reviewed
I think it should stay as required, I don't really see a use case for that (simple debugging is easier when you have the sierra in the file too imo)

2023-12-21 12:14 UTC, Arcticae commented
@piotmag769 if you want to omit writing file to the hard drive it's really useful since you would just call the binary in other process and read from stdout instead of performing read and write from disk (which is much more expensive)

2023-12-21 12:14 UTC, Arcticae approved these changes

2023-12-21 12:16 UTC, Arcticae requested changes
Actually we should e2e test this somehow (match the output against a regex?)

2023-12-21 12:18 UTC, Arcticae approved these changes
Ignore my last review lol i didn't notice the test

2023-12-21 13:36 UTC, piotmag769 commented on src/main.rs
> +                .append(false)
I think we need `truncate(true)` too
https://stackoverflow.com/questions/65782872/how-to-delete-the-contents-of-a-file-before-writing-to-it

2023-12-21 13:43 UTC, piotmag769 commented on tests/e2e.rs
> +    fs::remove_dir_all(temp_dir).unwrap();
Unnecessary

2023-12-21 13:43 UTC, piotmag769 commented on tests/e2e.rs
> +    let snapbox = prepare_runner(args, &temp_dir);
I think it should be rebased, the names changed

2023-12-22 08:59 UTC, merged